-- Constraints (primary key, foreign key) are not used in the junit test database

CREATE TABLE USER (
  USER_NAME varchar(100),
  EMAIL varchar(100),
  PASSWORD varchar(100)
);

CREATE TABLE USER_SESSION (
  USER_NAME varchar(100),
  SESSION_ID varchar(100),
  CREATE_DATE timestamp,
  EXPIRED BOOLEAN
);

CREATE TABLE BLOG_SPACE (
  ID  bigint generated by default as identity (start with 1 increment by 1) primary key ,
  OWNER varchar(100),
  URI varchar(100)
);


CREATE TABLE CONTRIBUTORS (
  USER_NAME varchar(100),
  SPACE_ID bigint
);

CREATE TABLE BLOG_ENTRY (
  ID  bigint generated by default as identity (start with 1 increment by 1) primary key ,
  AUTHOR varchar(100),
  SPACE_ID bigint,
  URI varchar(100),
  APPROVED BOOLEAN
);